use_frameworks!
platform :ios, '10.0'

def setup_pods
    pod 'UIColor-HexUtils', path: '../../'
end

target 'UIColor-HexUtilsExample' do
    setup_pods
end

target 'UIColor-HexUtilsExampleTests' do
    setup_pods
end
